# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Leeds_pgr_basic"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "Simple responsive Hugo theme for websites maintained by PGRs at the Leeds School of Mathematics"
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Gautam Chaudhuri"
  homepage = "https://gchaudhuri.dev"
